export const INITIAL_STATE_CONTACTS = [

  {
    id: 1,
    image: "https://www.svgrepo.com/show/105517/user-icon.svg",
    name: "Domagoj",
    lastName: "Guncevic",
    city: "Zenica",
    postCode: "10001",
    age: "30",
    gender: "Male",
    dob: null,
    street: "Crkvice 31",
    email: "dguncevic@gmail.com",
    phoneNumber: "0958142701",
  },
  {
    id: 2,
    image: "https://www.svgrepo.com/show/105517/user-icon.svg",
    name: "Filip",
    lastName: "Spanovic",
    city: "Osijek",
    postCode: "31000",
    age: "35",
    gender: "Male",
    dob: null,
    street: "Negdje u tenju",
    email: "fspanovic@gmail.com",
    phoneNumber: "0992134566",
  },
  {
    id: 3,
    image: "https://www.svgrepo.com/show/105517/user-icon.svg",
    name: "Ana",
    lastName: "Kovacevic",
    city: "Zagreb",
    postCode: "10000",
    age: "28",
    gender: "Female",
    dob: null,
    street: "Savska 15",
    email: "akovacevic@gmail.com",
    phoneNumber: "0912345678",
  },
  {
    id: 4,
    image: "https://www.svgrepo.com/show/105517/user-icon.svg",
    name: "Marko",
    lastName: "Juric",
    city: "Split",
    postCode: "21000",
    age: "40",
    gender: "Male",
    dob: null,
    street: "Poljudska 22",
    email: "mjuric@gmail.com",
    phoneNumber: "0987654321",
  },
  {
    id: 5,
    image: "https://www.svgrepo.com/show/105517/user-icon.svg",
    name: "Ivana",
    lastName: "Peric",
    city: "Rijeka",
    postCode: "51000",
    age: "26",
    gender: "Female",
    dob: null,
    street: "Korzo 12",
    email: "iperic@gmail.com",
    phoneNumber: "0976543210",
  },
  {
    id: 6,
    image: "https://www.svgrepo.com/show/105517/user-icon.svg",
    name: "Luka",
    lastName: "Maric",
    city: "Dubrovnik",
    postCode: "20000",
    age: "32",
    gender: "Male",
    dob: null,
    street: "Stradun 8",
    email: "lmaric@gmail.com",
    phoneNumber: "0998765432",
  },
  {
    id: 7,
    image: "https://www.svgrepo.com/show/105517/user-icon.svg",
    name: "Mia",
    lastName: "Zoric",
    city: "Pula",
    postCode: "52100",
    age: "24",
    gender: "Female",
    dob: null,
    street: "Forum 7",
    email: "mzoric@gmail.com",
    phoneNumber: "0954321765",
  },
  {
    id: 8,
    image: "https://www.svgrepo.com/show/105517/user-icon.svg",
    name: "Ivan",
    lastName: "Lovric",
    city: "Vukovar",
    postCode: "32000",
    age: "45",
    gender: "Male",
    dob: null,
    street: "Vukovarska 4",
    email: "ilovric@gmail.com",
    phoneNumber: "0923456789",
  },
  {
    id: 9,
    image: "https://www.svgrepo.com/show/105517/user-icon.svg",
    name: "Petra",
    lastName: "Radic",
    city: "Varazdin",
    postCode: "42000",
    age: "29",
    gender: "Female",
    dob: null,
    street: "Ban Jelacic 9",
    email: "pradic@gmail.com",
    phoneNumber: "0919876543",
  },
  {
    id: 10,
    image: "https://www.svgrepo.com/show/105517/user-icon.svg",
    name: "Josip",
    lastName: "Mikic",
    city: "Zadar",
    postCode: "23000",
    age: "38",
    gender: "Male",
    dob: null,
    street: "Kalelarga 14",
    email: "jmikic@gmail.com",
    phoneNumber: "0983216547",
  }
];
